INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('shred', '$2a$10$MshQV3.M/KWHZDdrEkT7yOCezdSbWo4fdFadrShQRyVFXqtTVDbby', true);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('admin', '$2a$10$MshQV3.M/KWHZDdrEkT7yOCezdSbWo4fdFadrShQRyVFXqtTVDbby', true);
INSERT INTO AUTHORITIES(username, authority) VALUES ('shred', 'ROLE_USER');
INSERT INTO AUTHORITIES(username, authority) VALUES ('admin', 'ROLE_ADMIN');